#!/bin/bash

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias cd..="cd .."
alias cds="cd ~/Sites"
alias c='xclip -selection clipboard'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias ch="history -c && > ~/.bash_history"
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias ll="ls -al"
alias l="ls -lh"
alias map="xargs -n1"
alias path='printf "%b\n" "${PATH//:/\\n}"'
alias rm="rm -rf --"
alias publish="node ~/Projects/NodeJs/note-publisher/index.js"
alias j="z" # auto-jump
alias dc="docker-compose"
alias d="ddev"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Load OS specific aliases.

. "aliases/$OS/bash_aliases"
